export const STORES_ADD = "STORES_ADD";
export const STORES_LOADING = "STORES_LOADING";
export const STORES_FAILED = "STORES_FAILED";
export const MAINCAT_ADD = "MAINCAT_ADD";
export const MAINCAT_LOADING = "MAINCAT_LOADING";
export const MAINCAT_FAILED = "MAINCAT_FAILED";
